### PR TITLE
Return error on table not found

### PR DESCRIPTION
**Pull request by liveforeverx**

### CODE REVIEW

**Comment by skirino** [comment]
What do you want to achieve in this PR?
If I understand you correctly, you want `RaftKV.command/4` and `query/4` to return `{:error, :table_not_found}` when the specified keyspace hasn't been registered.
When one forgot to register a keyspace, that's a terrible logic error and thus we should immediately make the caller crash.

**Comment by liveforeverx** [comment]
I want to achieve in starting phase, where cluster not established yet(not connected to other nodes), that it still possible to answer some specific requests.

It could happen only short time after start, till the node is connected to other nodes and has replicated all information.

The need is, because we save cluster information on some extern place and access it to initially connect to a cluster. But the same access layer is used to cache some cluster state, which we fetch from extern place too.

There are 3 options for me
1) `try/catch` on every operation
2) clone API, so that I explicitly know, if I should use clustered cache or not for this information, or add flag `:no_cache`
3) propagate error (which my pull request allows) without try/catch

**Comment by skirino** [comment]
I'm not sure what you mean.

> I want to achieve in starting phase, where cluster not established yet(not connected to other nodes), that it still possible to answer some specific requests.

It seems to me that It's not related to how `RaftKV.query/4` notify an error.
What are you going to do when `{:error, :table_not_found}` is returned?

**Comment by liveforeverx** [comment]
If cluster established:

* Get from raft_kv
* If not available, than request extern source
* Put information to cluster state

If cluster not established:

* Get from raft_kv
* Always not available, request extern source (request information, which other nodes are there)
* Try to put information to cluster state, so again not available, than ignore

This means, if other node try to access the same information, it is still not cached in `raft_kv` and they should go to other node.

If this cache layer is not available, than it will be ignored in our case, so in this case nodes must go to extern source than.

**Comment by skirino** [comment]
Then you are not trying to make it "still possible to answer some specific requests".
Anyway, my understanding is that you simply shouldn't call `RaftKV.query/4` before completion of `RaftKV.init()`.
I'm closing this as I want to stick with raising exception by `RaftKV.query/4`.

**Pull request closed without merging**
